### ISSUE TITLE
Issue with consumer-app and the dashboard does not load properly

### ISSUE THREAD

**Issue by raghubanda** [strimzi/strimzi-lab#27]
The dashboard does not load and attached screenshot 
Back-off | Back-off restarting failed container18 times in the last

-- | --

the logs of the pod looks like below 

  | 2019-08-09 14:09:43 INFO  ConsumerConfig:223 - ConsumerConfig values:
-- | --
  | auto.commit.interval.ms = 5000
  | auto.offset.reset = earliest
  | bootstrap.servers = [my-cluster-kafka-bootstrap:9092]
  | check.crcs = true
  | client.id =
  | connections.max.idle.ms = 540000
  | enable.auto.commit = true
  | exclude.internal.topics = true
  | fetch.max.bytes = 52428800
  | fetch.max.wait.ms = 500
  | fetch.min.bytes = 1
  | group.id = consumer-app
  | heartbeat.interval.ms = 3000
  | interceptor.classes = null
  | internal.leave.group.on.close = true
  | isolation.level = read_uncommitted
  | key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
  | max.partition.fetch.bytes = 1048576
  | max.poll.interval.ms = 300000
  | max.poll.records = 500
  | metadata.max.age.ms = 300000
  | metric.reporters = []
  | metrics.num.samples = 2
  | metrics.recording.level = INFO
  | metrics.sample.window.ms = 30000
  | partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
  | receive.buffer.bytes = 65536
  | reconnect.backoff.max.ms = 1000
  | reconnect.backoff.ms = 50
  | request.timeout.ms = 305000
  | retry.backoff.ms = 100
  | sasl.jaas.config = null
  | sasl.kerberos.kinit.cmd = /usr/bin/kinit
  | sasl.kerberos.min.time.before.relogin = 60000
  | sasl.kerberos.service.name = null
  | sasl.kerberos.ticket.renew.jitter = 0.05
  | sasl.kerberos.ticket.renew.window.factor = 0.8
  | sasl.mechanism = GSSAPI
  | security.protocol = PLAINTEXT
  | send.buffer.bytes = 131072
  | session.timeout.ms = 10000
  | ssl.cipher.suites = null
  | ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
  | ssl.endpoint.identification.algorithm = null
  | ssl.key.password = null
  | ssl.keymanager.algorithm = SunX509
  | ssl.keystore.location = null
  | ssl.keystore.password = null
  | ssl.keystore.type = JKS
  | ssl.protocol = TLS
  | ssl.provider = null
  | ssl.secure.random.implementation = null
  | ssl.trustmanager.algorithm = PKIX
  | ssl.truststore.location = null
  | ssl.truststore.password = null
  | ssl.truststore.type = JKS
  | value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
  |  
  | Aug 09, 2019 2:09:45 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2895 ms, time limit is 2000
  | Aug 09, 2019 2:09:46 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3895 ms, time limit is 2000

2019-08-09 14:10:37 INFO  Consumer:80 - Received on topic=iot-temperature-max, partition=0, offset=1370, key=d-f5baf508-db86-49cb-8f3f-7d3bca454386, value=22
--
  | 2019-08-09 14:10:38 INFO  Consumer:80 - Received on topic=iot-temperature-max, partition=0, offset=1371, key=d-f5baf508-db86-49cb-8f3f-7d3bca454386, value=22
  | 2019-08-09 14:10:39 INFO  Consumer:80 - Received on topic=iot-temperature-max, partition=0, offset=1372, key=d-f5baf508-db86-49cb-8f3f-7d3bca454386, value=22

**Comment by raghubanda** [comment]
2019-08-09 14:41:00 WARN  ClientUtils:54 - Removing server my-cluster-kafka-bootstrap:9092 from bootstrap.servers as DNS resolution failed for my-cluster-kafka-bootstrap
--
  | Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
  | at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:789)
  | at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:608)
  | at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getRestoreConsumer(DefaultKafkaClientSupplier.java:42)
  | at org.apache.kafka.streams.processor.internals.StreamThread.create(StreamThread.java:672)
  | at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:661)
  | at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:509)
  | at io.strimzi.streams.TemperatureDemo.run(TemperatureDemo.java:157)
  | at io.strimzi.streams.TemperatureDemo.main(TemperatureDemo.java:91)
  | Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
  | at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)
  | at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:706)
  | ... 7 more

**Comment by raghubanda** [comment]
ug 09, 2019 2:41:57 PM io.vertx.core.impl.BlockedThreadChecker
--
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2198 ms, time limit is 2000
  | Aug 09, 2019 2:41:58 PM io.vertx.core.impl.BlockedThreadChecker
  | WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3198 ms, time limit is 2000
  | 2019-08-09 14:41:58 INFO  Consumer:67 - HTTP server started on port 8080
  | 2019-08-09 14:42:04 INFO  AppInfoParser:109 - Kafka version : 1.0.0
  | 2019-08-09 14:42:04 INFO  AppInfoParser:110 - Kafka commitId : aaa7af6d4a11b29d
  | 2019-08-09 14:42:06 INFO  AbstractCoordinator:341 - [Consumer clientId=consumer-1, groupId=consumer-app] Discovered coordinator my-cluster-kafka-0.my-cluster-kafka-brokers.kafkaproject.svc.cluster.local:9092 (id: 2147483647 rack: null)
  | 2019-08-09 14:42:06 INFO  ConsumerCoordinator:341 - [Consumer clientId=consumer-1, groupId=consumer-app] Revoking previously assigned partitions []
  | 2019-08-09 14:42:06 INFO  AbstractCoordinator:336 - [Consumer clientId=consumer-1, groupId=consumer-app] (Re-)joining group
  | 2019-08-09 14:42:09 INFO  AbstractCoordinator:341 - [Consumer clientId=consumer-1, groupId=consumer-app] Successfully joined group with generation 39
  | 2019-08-09 14:42:09 INFO  ConsumerCoordinator:341 - [Consumer clientId=consumer-1, groupId=consumer-app] Setting newly assigned partitions []
  | Aug 09, 2019 2:42:09 PM io.vertx.core.impl.ContextImpl
  | SEVERE: Unhandled exception
  | java.util.NoSuchElementException: No value present
  | at java.util.Optional.get(Optional.java:135)
  | at io.strimzi.Consumer.lambda$main$2(Consumer.java:90)
  | at io.vertx.kafka.client.common.impl.Helper.lambda$adaptHandler$4(Helper.java:80)
  | at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl$1.lambda$onPartitionsAssigned$1(KafkaReadStreamImpl.java:91)
  | at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)

**Comment by raghubanda** [comment]
this works fine in minishift
